<?php self::$js->add('esconnect'); ?>
<?php self::$css->add('esconnect'); ?>
<form id="ESConnect" class="FormConnect form-inline">
    <div>
        <h2>Connect to ElasticSearch</h2>
    </div>
    <div>
        <input type="text" name="host" placeholder="Host" class="form-control">&nbsp;
        <input type="text" name="port" placeholder="Port" class="form-control">&nbsp;
        <input type="button" name="BtnConnect" class="btn btn-primary" value="Connect">
    </div>
</form>
