<?php self::$js->add('admin'); ?>
<?php
    $esinfo = self::$app->esconnect();
    $indices = self::$app->esindexes();
    $uri = self::$uri->arr();
?>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">ElasticSearch&nbsp;<span class="label label-success"><?php echo $esinfo['version']['number']; ?></span></a>
    </div>
    <p class="navbar-text">
        <strong>Lucene Version:</strong>&nbsp;<span class="label label-success"><?php echo $esinfo['version']['lucene_version']; ?></span>&nbsp;
        <strong>Build Timestamp:</strong>&nbsp;<span class="label label-success"><?php echo $esinfo['version']['build_timestamp']; ?></span>&nbsp;
    </p>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
        <li><a href="/exit">Exit</a></li>
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid">
    <div class="col-md-1">
        <h3>Indices</h3>
<div class="btn-group-vertical" role="group" aria-label="">
            <?php
                foreach(array_keys($indices) as $i=>$index){
echo <<<HTML
    <div class="btn-group" role="group">
        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            $index <span class="caret"></span>
         </button>
        <ul class="dropdown-menu">
HTML;
foreach(array_keys($indices[$index]['mappings']) as $type){
    echo '<li><a href="/index/'.$index.'/'.$type.'" link>'.$type.'</a></li>';
}
echo <<<HTML
        </ul>
    </div>
HTML;
                }
            ?>
        </div>
    </div>
    <div class="col-md-11">
<?php
    if(isset($uri[0])){
        if($uri[0] == 'index' && (isset($uri[1]) && isset($uri[2]))){
            $index = $uri[1].'/'.$uri[2];
            echo '<table class="table" id="docs" data-index="'.$index.'"><thead><tr><th width="1">_id</th><th>_source</th><th width="1">action</th><thead><tbody>';
            $db = self::$app->es();
            $query = [
                "size"=>150,
                "from"=>0
            ];
            $list = $db->index($index.'/_search')->post($query);
            foreach($list['hits']['hits'] as $doc){
                echo '<tr><td>'.$doc['_id'].'</td><td>'.json_encode($doc['_source']).'</td><td><span class="glyphicon glyphicon-remove" style="cursor:pointer;color:red;" aria-hidden="true" data-id="'.$doc['_id'].'"></span></td></tr>';
            }
            echo '</tbody></table>';
        }
    }
?>

    </div>
</div>
